name: quant_finance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - polars
  - scikit-learn
  - xgboost
  - tensorflow
  - keras
  - scipy
  - matplotlib
  - plotly
  - seaborn
  - streamlit
  - alpaca-py
  - bs4
  - selenium
  - pip
  - pip:
      - backtesting
      - ta
      - yfinance
      - arch
      - dotenv
      - polygon-api-client
      - pandas_datareader
      - webdriver-manager
      - SQLite3-0611
      - apache-airflow
      - kafka-python
      - psycopg2-binary
      - hmmlearn
      - hurst
      - qfin