# This is a conda environment for the repository
name: quant_finance
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - keras
  - alpaca-py
  - python-dotenv
  - yfinance
  - arch